Show GPU subsystem name if possible. Fixes #1490
dylanaraps/neofetch pull request #1648
Opened 2021-01-03 04:29 UTC by quantum5

## Description

After this change, if a subsystem name exists for a GPU, display that name instead of the device name. This should fix the issue mentioned in #1490. For example, a card that would be shown as `GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590` before will now be shown as `GPU: AMD ATI Radeon RX 480 4GB`. This fallback logic is implemented in the `awk` command.

Additionally, the PCI address is now stripped from the awk output because it never is desirable to print it. It is, however, still kept internally in `awk` to distinguish multiple cards of the same model.

## Features

Implements #1490.

2021-02-16 22:20 UTC, gitfib requested changes
It breaks Nvidia ("Device [device id]", when there's no real subsystem name)
How about `$7 ~ /^$|^Device [0-9]+$/` for the subsystem check?

2021-02-16 23:35 UTC, quantum5 commented
> It breaks Nvidia ("Device [device id]", when there's no real subsystem name)
> How about `$7 ~ /^$|^Device [0-9]+$/` for the subsystem check?

I don't personally have a card that shows up as "Device [device id]", but I changed it anyways.

2021-02-17 00:09 UTC, gitfib approved these changes
Perfect, at least for my cards, thanks!

2021-02-25 22:58 UTC, gitfib requested changes
Actually that's in hex, so that would be... `$7 ~ /^$|^Device [[:xdigit:]]+$/`
PS. you might have other, non-gpu devices in `lspci -mm` that would show up as such in the last field

2021-02-25 23:23 UTC, quantum5 commented
> Actually that's in hex, so that would be... `$7 ~ /^$|^Device [[:xdigit:]]+$/`

Fixed.

> PS. you might have other, non-gpu devices in `lspci -mm` that would show up as such in the last field

I don't, and they would be filtered out by `/"Display|"3D|"VGA/`.

2021-02-25 23:31 UTC, gitfib approved these changes

2021-03-21 21:01 UTC, pseregiet commented
@quantum5 I've checked out your branch and it makes no difference for me. Same result as on master. That is: GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 (my card is rx 590). I noticed today while browsing firefox settings that the webGL1 detects my gpu correctly: 

WebGL 1 Driver Renderer	AMD -- Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.6-138-tkg-upds, LLVM 11.1.0)

2021-03-21 21:07 UTC, gitfib commented
> @quantum5 I've checked out your branch and it makes no difference for me. Same result as on master. That is: GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 (my card is rx 590). I noticed today while browsing firefox settings that the webGL1 detects my gpu correctly:
> 
> WebGL 1 Driver Renderer AMD -- Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.6-138-tkg-upds, LLVM 11.1.0)

Can you post your `lspci -mmnn | grep VGA`? Maybe it's not known by `lspci` (http://pci-ids.ucw.cz/)

2021-03-21 22:01 UTC, quantum5 commented
@pseregiet You might need to update your PCI IDs file with `sudo update-pciids`. If it still doesn't work, you can add your subsystem on https://pci-ids.ucw.cz/read/PC/1002/67df.

2021-03-21 22:56 UTC, pseregiet commented
this is the output:
lspci -mmnn | grep VGA
08:00.0 "VGA compatible controller [0300]" "Advanced Micro Devices, Inc. [AMD/ATI] [1002]" "Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [67df]" -re1 "Tul Corporation / PowerColor [148c]" "Device [2391]"

I've added my gpu on https://pci-ids.ucw.cz/read/PC/1002/67df Although I think I've done something wrong because the name is still blank in the table at the bottom (id 148c 2391)

2021-03-21 22:59 UTC, quantum5 commented
@pseregiet I think this is expected. It need manual review, which took a few days for my card. Once that's done, you can run `sudo update-pciids` and it should work.

2021-03-21 23:02 UTC, pseregiet commented
Alright, we'll see if it works.

2021-06-11 07:39 UTC, merged

2021-06-11 20:02 UTC, pseregiet commented
Hey. After this was merged neofetch reports my gpu as:
GPU: AMD ATI Red Devil
My card is on the pci-ids (https://pci-ids.ucw.cz/read/PC/1002/67df/148c2391) and has a proper name

2021-06-11 20:13 UTC, quantum5 commented
@pseregiet did you run `sudo update-pciids` to update the database?

2021-07-31 19:38 UTC, pseregiet commented
@quantum5 Hey, sorry for late response. That didn't help. I think there's a problem with the striping of the string, because the name of my gpu contains 2 strings between square brackets. "Advanced Micro Devices, Inc. **[AMD/ATI]** Radeon RX 590 **[Red Devil]**"

2021-07-31 19:59 UTC, pseregiet commented
```
                         gpu="${gpu/\[AMD\] }"
                         gpu="${gpu/OEM }"
                         gpu="${gpu/Advanced Micro Devices, Inc.}"
-                        gpu="${gpu/*\[}"
-                        gpu="${gpu/\]*}"
+                        gpu=$(echo ${gpu} | sed -e 's/\[[^][]*\]//g')
                         gpu="$brand $gpu"
                     ;;

```
this fixes the problem. I don't know how to do it in pure bash but I'm sure you can figure it out.
```
[oxi@manjaro neofetch]$ ./neofetch
                   -`                    oxi@manjaro
                  .o+`                   -----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: A320M-S2H
               `+oooooo:                 Kernel: 5.13.4-182-tkg-pds
               -+oooooo+:                Uptime: 3 hours, 55 mins
             `/:-:++oooo+:               Packages: 1378 (pacman)
            `/++++/+++++++:              Shell: bash 5.1.8
           `/++++++++++++++:             Resolution: 2560x1440
          `/+++ooooooooooooo/`           WM: i3
         ./ooosssso++osssssso+`          Theme: Adwaita-dark [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       Terminal Font: Source Code Pro
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon RX 590
  `+sso+:-`                 `.-/+oso:    Memory: 4619MiB / 15954MiB
```